### ISSUE TITLE
Set Game result

### ISSUE THREAD

**Issue by ratosh** [AndyGrant/TexelSets#1]
I´ve found a few entries in Ethereal Set with results that does not match 7 piece end game result.

**Comment by AndyGrant** [comment]
Positions were generated from games with Ethereal at 2+.02s time control. So I'de not be surprised to see some suboptimal results here and there.

As another note though, it may be of interest to only use positions with > 7 pieces, as we can assume 6man Syzygy + the ability to understand a single trade while playing under real conditions.
